export const STAGES = ['START', 'PREVIEW_QUIZ', 'PREVIEW_QUESTION', 'QUESTION_AND_ANSWER', 'RESULT', 'SCORE_RESULT', 'FINISH'];

export const STAGE = {
    START: 'START',
    PREVIEW_QUIZ: 'PREVIEW_QUIZ',
    PREVIEW_QUESTION: 'PREVIEW_QUESTION',
    QUESTION_AND_ANSWER: 'QUESTION_AND_ANSWER',
    RESULT: 'RESULT',
    SCORE_RESULT: 'SCORE_RESULT',
    FINISH: 'FINISH'
}
